# Generated by Django 6.0.1 on 2026-02-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='receipt_id',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
