# Generated by Django 6.0.1 on 2026-02-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataBuilder", "0002_rename_product_id_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["datetime"], name="DataBuilder_datetim_5e6d9d_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="DataBuilder_product_1dc9b6_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["receipt"], name="DataBuilder_receipt_bfa274_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="DataBuilder_name_ce745a_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand"], name="DataBuilder_brand_i_99689e_idx"),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(fields=["shop"], name="DataBuilder_shop_id_a9f575_idx"),
        ),
        migrations.AddIndex(
            model_name="shop",
            index=models.Index(fields=["name"], name="DataBuilder_name_79260e_idx"),
        ),
    ]
