# Generated by Django 6.0.1 on 2026-02-11 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataBuilder", "0003_cartitem_databuilder_datetim_5e6d9d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="receipt",
            name="DataBuilder_shop_id_a9f575_idx",
        ),
    ]
