# Generated by Django 6.0.1 on 2026-02-11 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataBuilder", "0004_remove_receipt_databuilder_shop_id_a9f575_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cartitem",
            name="DataBuilder_datetim_5e6d9d_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="DataBuilder_product_1dc9b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="DataBuilder_receipt_bfa274_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="DataBuilder_name_ce745a_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="DataBuilder_brand_i_99689e_idx",
        ),
        migrations.RemoveIndex(
            model_name="shop",
            name="DataBuilder_name_79260e_idx",
        ),
    ]
